---
- name: HA mode
  when: pihole_ha_mode and master | bool
  block:
    - name: Start/Update orbital-sync container
      community.docker.docker_container:
        name: orbital-sync
        image: mattwebbio/orbital-sync:1.8.1
        pull: true
        restart_policy: unless-stopped
        state: started
        env:
          PRIMARY_HOST_BASE_URL: "http://{{ hostvars['pihole-master'].inventory_hostname }}"
          PRIMARY_HOST_PASSWORD: '{{ pihole_webpassword }}'
          SECONDARY_HOSTS_1_BASE_URL: "http://{{ hostvars['pihole-slave'].inventory_hostname }}"
          SECONDARY_HOSTS_1_PASSWORD: "{{ pihole_webpassword }}"
          INTERVAL_MINUTES: '15'

    - name: Remove old image versions
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: false

- name: Single mode
  when: not pihole_ha_mode | bool
  block:
    - name: Remove orbital-sync container
      community.docker.docker_container:
        name: orbital-sync
        state: absent

