dnsservers:
  hosts: 
    pihole-master:
      ansible_host: 192.168.16.2
      priority: 101
      slave: false
    pihole-slave:
      ansible_host: 192.168.16.3
      priority: 100
      slave: true
