---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.docker
    version: 3.11.0
  - name: community.general
    version: 9.3.0
  - name: ansible.utils
    version: 5.1.1
roles:
  # from galaxy
  - name: geerlingguy.docker
    version: 7.3.0
