---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.docker
    version: 4.1.0
  - name: community.general
    version: 10.0.1
  - name: ansible.utils
    version: 5.1.2
roles:
  # from galaxy
  - name: geerlingguy.docker
    version: 7.4.3
