---
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.docker
    version: 4.0.0
  - name: community.general
    version: 10.0.1
  - name: ansible.utils
    version: 5.1.2
roles:
  # from galaxy
  - name: geerlingguy.docker
    version: 7.4.1
