---
dependency:
  enabled: true
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance-1
    image: geerlingguy/docker-debian12-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    published_ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:53:53
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    groups:
      - dnsservers

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles/"
    ANSIBLE_VERBOSITY: 0
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../group_vars
    host_vars:
      instance-1:
        slave: false

verifier:
  name: ansible
