---
- name: Verify
  hosts: all

  tasks:
    - name: Check PiHole services and connectivities
      loop:
        - 80
        - 53
        - 4711
      loop_control:
        loop_var: port
      ansible.builtin.wait_for:
        host: "127.0.0.1"
        port: "{{ port }}"
        timeout: 120

    - name: Perform DNS lookup
      ansible.builtin.set_fact:
        dns_result: "{{ lookup('community.general.dig', 'www.google.com.', '127.0.0.1') }}"

    - name: Verify DNS lookup
      ansible.builtin.assert:
        that: dns_result is defined and dns_result != ""
        fail_msg: "DNS server did not return a value for DNS lookup www.google.com"
        success_msg: "DNS server returned value: {{ dns_result }}"
