# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - master
      - dev
      - feature/*
  pull_request:
    branches:
      - master
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: 'ansible-pihole-cluster'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Install test dependencies.
      #   run: ansible-galaxy role install -r roles/requirements.yml
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'

  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   path: "${{ github.repository }}"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install molecule molecule-plugins[docker] yamllint ansible-lint dnspython
      - name: Test Ansible Bootstrap
        run: |
          molecule test --all
        env:
          PY_COLORS: 1
